// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-wbggZSI_aFGa-_9W08pZDW5H7U2ejZc',
    appId: '1:1043072576396:web:84dd640914e4f7dccf04a9',
    messagingSenderId: '1043072576396',
    projectId: 'camera-app-e2db9',
    authDomain: 'camera-app-e2db9.firebaseapp.com',
    storageBucket: 'camera-app-e2db9.appspot.com',
    measurementId: 'G-WL2WZ637N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvnZE40d-oGS0_VudC8taCYHcBwsYfPbk',
    appId: '1:1043072576396:android:c7167bb1b67e519ccf04a9',
    messagingSenderId: '1043072576396',
    projectId: 'camera-app-e2db9',
    storageBucket: 'camera-app-e2db9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADYtts_ZRKVUmxq7E-GL8oTsJwIJJ9Rbo',
    appId: '1:1043072576396:ios:d011f84f0e555dcdcf04a9',
    messagingSenderId: '1043072576396',
    projectId: 'camera-app-e2db9',
    storageBucket: 'camera-app-e2db9.appspot.com',
    iosBundleId: 'com.example.cameraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADYtts_ZRKVUmxq7E-GL8oTsJwIJJ9Rbo',
    appId: '1:1043072576396:ios:f653b91d9498c8decf04a9',
    messagingSenderId: '1043072576396',
    projectId: 'camera-app-e2db9',
    storageBucket: 'camera-app-e2db9.appspot.com',
    iosBundleId: 'com.example.cameraApp.RunnerTests',
  );
}
